services:
  active_sinatra:
    restart: unless-stopped
    image: donkirkby/active-sinatra-devcontainer:v0.2.2
    environment:
      - EXAMPLE_VALUE
      - EXAMPLE_VALUE2=from-compose-file
    volumes:
      - .:/opt/active_sinatra
