development:
    adapter: 'oracle_enhanced'
    database: 'FREEPDB1'  # alias in config/tnsnames.ora
    username: 'dev'
    password: 'dev'

test:
    adapter: 'oracle_enhanced'
    database: 'FREEPDB1'  # alias in config/tnsnames.ora
    username: 'dev'
    password: 'dev'