development:
  adapter: oracle_enhanced
  database: LOCAL_DATABASE
  username: <%= ENV['QAI_DB_USERNAME'] %>
  password: <%= ENV['QAI_DB_PASSWORD'] %>

test:
  adapter: sqlite3
  database: db/test.sqlite3